LeasedLineTools/src/objects/BT_Wholesale_Product__c.object
<CustomObject>
    <fields>
        <fullName>Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fibre</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bandwidth__c</fullName>
        <label>Bandwidth</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bearer__c</fullName>
        <label>Bearer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_Price__c</fullName>
        <label>Connection Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Etherflow_Pricing__c</fullName>
        <label>Etherflow Pricing</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hub_Site_Postcode__c</fullName>
        <label>Hub Site Postcode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Term__c</fullName>
        <label>Product Term</label>
        <picklist>
            <picklistValues>
                <fullName>1 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Year</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rental_Price__c</fullName>
        <label>Rental Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>BT Wholesale Product</label>
    <nameField>
        <label>BT Wholesale Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BT Wholesale Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LeasedLineTools/src/objects/Talk_Talk_Product__c.object
<CustomObject>
    <fields>
        <fullName>Collector_Exchange_Name__c</fullName>
        <label>Collector Exchange Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distance__c</fullName>
        <label>Distance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ethernet_Exchange_Name__c</fullName>
        <label>Ethernet Exchange Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fibre_Exchange_Name__c</fullName>
        <label>Fibre Exchange Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <picklist>
            <picklistValues>
                <fullName>Installation Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Term__c</fullName>
        <label>Product Term</label>
        <picklist>
            <picklistValues>
                <fullName>1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>10MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100MB / 100MB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

LeasedLineTools/src/objects/Virgin_Media_Product__c.object
<CustomObject>
    <fields>
        <fullName>BPT_Quote__c</fullName>
        <label>BPT Quote</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bandwidth__c</fullName>
        <label>Bandwidth</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bearer__c</fullName>
        <label>Bearer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_Price__c</fullName>
        <label>Connection Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Flavour__c</fullName>
        <label>Flavour</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Term__c</fullName>
        <label>Product Term</label>
        <picklist>
            <picklistValues>
                <fullName>1 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Year</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rental_Price__c</fullName>
        <label>Rental Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Site_B_Access__c</fullName>
        <label>Site B Access</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Pricing_Summary__c</fullName>
        <label>Total Pricing Summary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Virgin Media Product</label>
    <nameField>
        <label>Virgin Media Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virgin Media Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LeasedLineTools/src/classes/LeasedLineQuoteResults.cls
public class LeasedLineQuoteResults {
    
    public List<Virgin_Media_Product__c> virginproducts;
    public List<Talk_Talk_Product__c> talktalkproducts;   
    public List<BT_Wholesale_Product__c> btproducts;
    public Opportunity oppt;
    
    public LeasedLineQuoteResults(ApexPages.StandardController controller) {
        this.oppt = (Opportunity)controller.getRecord();
    }
    
    public List<Virgin_Media_Product__c> getvirginproducts() {
        virginproducts = new List<Virgin_Media_Product__c>();
        virginproducts = [SELECT Bearer__c, Bandwidth__c, Product_Term__c, Connection_Price__c,
                                         Rental_Price__c, Total_Pricing_Summary__c, BPT_Quote__c, 
                                         Reference__c, Site_B_Access__c, Flavour__c
                          FROM Virgin_Media_Product__c];
        return virginproducts;   
    }
    
    public List<Talk_Talk_Product__c> gettalktalkproducts() {
        talktalkproducts = new List<Talk_Talk_Product__c>();
        talktalkproducts = [SELECT Product__c, Product_Term__c, Price__c, Product_Family__c,
                                   Fibre_Exchange_Name__c, Ethernet_Exchange_Name__c,
                                   Collector_Exchange_Name__c, Zone__c, Distance__c, Error_Message__c
                            FROM Talk_Talk_Product__c];
        return talktalkproducts;   
    }

    public List<BT_Wholesale_Product__c> getbtproducts() {
        btproducts = new List<BT_Wholesale_Product__c>();
        btproducts = [SELECT Bearer__c, Bandwidth__c, Product_Term__c, Etherflow_Pricing__c,
                                 Connection_Price__c, Rental_Price__c, Hub_Site_Postcode__c, Access_Type__c
                      FROM BT_Wholesale_Product__c];
        return btproducts;   
    }    
}