LeasedLineTools/src/objects/Leased_Line_Quote_Request__c.object
<CustomObject>
    <fields>
        <fullName>Bandwidth__c</fullName>
        <label>Bandwidth</label>
        <picklist>
            <picklistValues>
                <fullName>2MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>400MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>600MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>700MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>900MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1GB</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Bearer__c</fullName>
        <label>Bearer</label>
        <picklist>
            <picklistValues>
                <fullName>10MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1GB</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Contract_Term__c</fullName>
        <label>Contract Term</label>
        <picklist>
            <picklistValues>
                <fullName>1 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Years</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Diverse_Circuit__c</fullName>
        <label>Diverse Circuit</label>
        <picklist>
            <picklistValues>
                <fullName>RAO1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAO2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAO2 Plus</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Etherflow_Bandwidth__c</fullName>
        <label>Etherflow Bandwidth</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default CoS (Standard)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi Cos 5% (Premium)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi Cos 10% (Premium)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi Cos 25% (Premium)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi Cos 50% (Premium)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi Cos 100% (Premium)</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product_Option__c</fullName>
        <label>Product Option</label>
        <picklist>
            <picklistValues>
                <fullName>GEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ethernet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Leased Line Quote Request</label>
    <nameField>
        <label>Site Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leased Line Quote Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LeasedLineTools/src/classes/LeasedLineQuotes.cls
public class LeasedLineQuotes {
    public Opportunity oppt;
    //public List<Leased_Line_Quote_Request__c> quoteoptions;
    Leased_Line_Quote_Request__c llqr;
    String[] applications = new String[]{};
    
    public PageReference save(){
    //PageReference pageRef = new PageReference('http://www.google.com');
    //pageRef.setredirect(true);
    //return pageRef;
    insert llqr;
    return page.linecheckerresults;
    }       

    public LeasedLineQuotes(ApexPages.StandardController controller) {
        this.oppt = (Opportunity)controller.getRecord();
    } 
    
    public Leased_Line_Quote_Request__c getleasedlinequotefields(){
        llqr = new Leased_Line_Quote_Request__c();
        return llqr;
    }
    
    
    
    //Contract Term
    public List<SelectOption> CTOptions {
     get {
       List<SelectOption> options = new List<SelectOption>();
       for( Schema.PicklistEntry f : Leased_Line_Quote_Request__c.Contract_Term__c.getDescribe().getPicklistValues()) {
         options.add(new SelectOption(f.getValue(), f.getLabel()));
        } 
       return options;
     }  
     set;
    }
    
    //get and set the multi-select pick list as checkboxes
    public String[] CTItems { 
     get {
        String[] selected = new List<String>();
        List<SelectOption> sos = this.CTOptions;
        for(SelectOption s : sos) {
        if (this.llqr.Contract_Term__c!=null && this.llqr.Contract_Term__c.contains(s.getValue()))
           selected.add(s.getValue());
        }
        return selected;
     }public set {
        String selectedConcat = '';
        for(String s : value) {
         if (selectedConcat == '') 
           selectedConcat += s;
         else selectedConcat += ';' + s;
        }
        llqr.Contract_Term__c= selectedConcat;
     }
   }     
    
    
    //Product Options
    public List<SelectOption> ProdOptions {
     get {
       List<SelectOption> options = new List<SelectOption>();
       for( Schema.PicklistEntry f : Leased_Line_Quote_Request__c.Product_Option__c.getDescribe().getPicklistValues()) {
         options.add(new SelectOption(f.getValue(), f.getLabel()));
        } 
       return options;
     }  
     set;
    }
    
    //get and set the multi-select pick list as checkboxes
    public String[] ProdItems { 
     get {
        String[] selected = new List<String>();
        List<SelectOption> sos = this.ProdOptions;
        for(SelectOption s : sos) {
        if (this.llqr.Product_Option__c!=null && this.llqr.Product_Option__c.contains(s.getValue()))
           selected.add(s.getValue());
        }
        return selected;
     }public set {
        String selectedConcat = '';
        for(String s : value) {
         if (selectedConcat == '') 
           selectedConcat += s;
         else selectedConcat += ';' + s;
        }
        llqr.Product_Option__c= selectedConcat;
     }
   }     

    //Bearer
    public List<SelectOption> BearerOptions {
     get {
       List<SelectOption> options = new List<SelectOption>();
       for( Schema.PicklistEntry f : Leased_Line_Quote_Request__c.Bearer__c.getDescribe().getPicklistValues()) {
         options.add(new SelectOption(f.getValue(), f.getLabel()));
        } 
       return options;
     }  
     set;
    }
    
    //get and set the multi-select pick list as checkboxes
    public String[] BearerItems { 
     get {
        String[] selected = new List<String>();
        List<SelectOption> sos = this.CTOptions;
        for(SelectOption s : sos) {
        if (this.llqr.Bearer__c!=null && this.llqr.Bearer__c.contains(s.getValue()))
           selected.add(s.getValue());
        }
        return selected;
     }public set {
        String selectedConcat = '';
        for(String s : value) {
         if (selectedConcat == '') 
           selectedConcat += s;
         else selectedConcat += ';' + s;
        }
        llqr.Bearer__c= selectedConcat;
     }
   }   
    
    
    //Etherflow Bandwidth
    public List<SelectOption> EtherOptions {
     get {
       List<SelectOption> options = new List<SelectOption>();
       for( Schema.PicklistEntry f : Leased_Line_Quote_Request__c.Etherflow_Bandwidth__c.getDescribe().getPicklistValues()) {
         options.add(new SelectOption(f.getValue(), f.getLabel()));
        } 
       return options;
     }  
     set;
    }
    
    //get and set the multi-select pick list as checkboxes
    public String[] EtherItems { 
     get {
        String[] selected = new List<String>();
        List<SelectOption> sos = this.EtherOptions;
        for(SelectOption s : sos) {
        if (this.llqr.Etherflow_Bandwidth__c!=null && this.llqr.Etherflow_Bandwidth__c.contains(s.getValue()))
           selected.add(s.getValue());
        }
        return selected;
     }public set {
        String selectedConcat = '';
        for(String s : value) {
         if (selectedConcat == '') 
           selectedConcat += s;
         else selectedConcat += ';' + s;
        }
        llqr.Etherflow_Bandwidth__c= selectedConcat;
     }
   }   

    //Diverse Circuit
    public List<SelectOption> DCOptions {
     get {
       List<SelectOption> options = new List<SelectOption>();
       for( Schema.PicklistEntry f : Leased_Line_Quote_Request__c.Diverse_Circuit__c.getDescribe().getPicklistValues()) {
         options.add(new SelectOption(f.getValue(), f.getLabel()));
        } 
       return options;
     }  
     set;
    }
    
    //get and set the multi-select pick list as checkboxes
    public String[] DCItems { 
     get {
        String[] selected = new List<String>();
        List<SelectOption> sos = this.DCOptions;
        for(SelectOption s : sos) {
        if (this.llqr.Product_Option__c!=null && this.llqr.Diverse_Circuit__c.contains(s.getValue()))
           selected.add(s.getValue());
        }
        return selected;
     }public set {
        String selectedConcat = '';
        for(String s : value) {
         if (selectedConcat == '') 
           selectedConcat += s;
         else selectedConcat += ';' + s;
        }
        llqr.Diverse_Circuit__c= selectedConcat;
     }
   }       
    
    //Bandwidth
    public List<SelectOption> BandwidthOptions {
     get {
       List<SelectOption> options = new List<SelectOption>();
       for( Schema.PicklistEntry f : Leased_Line_Quote_Request__c.Bandwidth__c.getDescribe().getPicklistValues()) {
         options.add(new SelectOption(f.getValue(), f.getLabel()));
        } 
       return options;
     }  
     set;
    }
    
    //get and set the multi-select pick list as checkboxes
    public String[] BandwidthItems { 
     get {
        String[] selected = new List<String>();
        List<SelectOption> sos = this.BandwidthOptions;
        for(SelectOption s : sos) {
        if (this.llqr.Bandwidth__c!=null && this.llqr.Bandwidth__c.contains(s.getValue()))
           selected.add(s.getValue());
        }
        return selected;
     }public set {
        String selectedConcat = '';
        for(String s : value) {
         if (selectedConcat == '') 
           selectedConcat += s;
         else selectedConcat += ';' + s;
        }
        llqr.Bandwidth__c= selectedConcat;
     }
   }      

    
    
    
    //public List<Leased_Line_Quote_Request__c> getquoteoptions() {
    //    quoteoptions = [ SELECT id, name FROM Leased_Line_Quote_Request__c ];
    //    return quoteoptions;
    //}
    
          public String[] getcrmAppplications() {
        return applications;
    }
 
    public void setcrmAppplications(String[] applications) {
        this.applications = applications;
    }
 
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('BT EFM','BT EFM'));
        options.add(new SelectOption('TalkTalk EFM','TalkTalk EFM'));
        options.add(new SelectOption('TalkTalk Education','TalkTalk Education'));
        options.add(new SelectOption('Upgrade Option 1','Upgrade Option 1'));
        options.add(new SelectOption('Upgrade Option 2','Upgrade Option 2'));
        options.add(new SelectOption('Point to Point Circuit','Point to Point Circuit'));

        return options;
    }
    
    public Leased_Line_Quote_Request__c getllqr(){
        if (llqr == null) llqr = new Leased_Line_Quote_Request__c();
        return llqr;
    }           
}