LeasedLineTools/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Bandwidth__c</fullName>
        <label>Bandwidth</label>
        <picklist>
            <picklistValues>
                <fullName>10Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1Gb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bearer__c</fullName>
        <label>Bearer</label>
        <picklist>
            <picklistValues>
                <fullName>100Mb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1Gb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>lineProvider__c</fullName>
        <label>lineProvider</label>
        <picklist>
            <picklistValues>
                <fullName>Virgin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Talktalk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

LeasedLineTools/src/classes/TestUtil.cls
@isTest
public class TestUtil {
    
    static public void createTalktalkProducts()
	{
		//String[] bearers = new String[]{'100Mb', '1Gb'};
		//String[] bandwidths = new String[]{'10Mb', '20Mb', '30Mb', '40Mb', '50Mb', '100Mb', '200Mb', '300Mb', '500Mb', '1Gb'};
		String[] bearers = new String[]{'100Mb'};
		String[] bandwidths = new String[]{'10Mb', '20Mb'};
		String[] terms = new String[]{'1', '3'};
		String[] families = new String[]{'Installation Charges', 'Recurring Charges'};
		List<Product2> products2 = new List<Product2>();
		for (String bearer: bearers) {
			for (String bandwidth: bandwidths) {
				for (String term: terms) {
					for (String family: families) {
						Product2 prod = new Product2(
				    		Name = bandwidth + ' / ' + bearer + ' - ' + term + ' year',
				    		Bearer__c = bearer,
				    		Bandwidth__c = bandwidth,
				    		Term__c = term,
				    		Family = family,
				    		IsActive = true,
				    		lineProvider__c = 'Talktalk'
				    	);
				    	products2.add(prod);
					}
				}
			}
		}
		insert products2;
	}
}