LeasedLineTools/src/objects/Talk_Talk_Product__c.object
<CustomObject>
    <fields>
        <fullName>Collector_Exchange_Name__c</fullName>
        <label>Collector Exchange Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distance__c</fullName>
        <label>Distance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ethernet_Exchange_Name__c</fullName>
        <label>Ethernet Exchange Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fibre_Exchange_Name__c</fullName>
        <label>Fibre Exchange Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>10MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50MB / 100MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100MB / 100MB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Ref__c</fullName>
        <description>Leased Line Quote Request foreign key</description>
        <label>Site Ref</label>
        <referenceTo>Leased_Line_Quote_Request__c</referenceTo>
        <relationshipLabel>Talk Talk Products</relationshipLabel>
        <relationshipName>Talk_Talk_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

LeasedLineTools/src/classes/quoteoptions.cls
public class quoteoptions {

    public List<LLProducts> products;
        
    public List<LLProducts> getproducts() {
        products = new List<LLProducts>();
        String oppid = ApexPages.currentPage().getParameters().get('opportunityid');
        String siteref = ApexPages.currentPage().getParameters().get('siteref');
        for(Talk_Talk_Product__c ttp : [SELECT Name, Product__c, Connection_Price_1_Year__c, Connection_Price_3_Year__c,
                                   Rental_Price__c, Fibre_Exchange_Name__c, Ethernet_Exchange_Name__c,
                                   Collector_Exchange_Name__c, Zone__c, Distance__c
                           FROM Talk_Talk_Product__c
                            WHERE Site_Ref__c = 'a0Dg0000000Jd6w' ORDER BY Name Desc
                           ]){
                   products.add(new LLProducts(ttp));
        }
        return products;   
    }      
        
    public class LLProducts {
        
        public Talk_Talk_Product__c product { get; set; }
        public LLProducts(Talk_Talk_Product__c prod){
            product = prod;
            selected = false;
        }
        
        public String productname {
            get { return product.name; }
            set {}
        }
        
        public Decimal connectionprice1year {
            get { return product.Connection_Price_1_Year__c; }
            set {}
        }
        
        public Decimal connectionprice3year {
            get { return product.Connection_Price_3_Year__c; }
            set {}
        }
        
        public Decimal rentalprice {
            get { return product.Rental_Price__c; }  
            set {}
        }
        
        public String quantity {
            get { return product.Fibre_Exchange_Name__c; }  
            set {}
        }        
        
        public Boolean selected
                { get; set; }
    }        

}